packages/proxy/schema/index.ts

Support `mistral-tiny`, `mistral-small`, and `mistral-medium`

Add support for Mistral

---

packages/proxy/schema/index.ts

Contributed by @CitrusTechnology

Add new model endpoints

---

apis/cloudflare/src/index.ts

It seems we already have this in the nodeJS one, and there is a landing page for the vercel one which should also suffice.

Create a hello world endpoint for the proxy.

---

packages/proxy/package.json
packages/proxy/schema/index.ts
packages/proxy/src/proxy.ts

Move typedefs to @braintrust/core

---

apis/cloudflare/src/proxy.ts
packages/proxy/edge/index.ts

This enables more advanced cors

Send exact origin (matching whitelist)

---

packages/proxy/schema/index.ts
packages/proxy/schema/secrets.ts
packages/proxy/src/providers/anthropic.ts
packages/proxy/src/proxy.ts

Adds support for multimodal content, currently just for `gpt-4-vision-preview` and the `claude-3` variants.

Add support for multimodal message content

---

packages/proxy/src/providers/anthropic.ts

Per [this guide](https://docs.anthropic.com/claude/docs/tool-use#chain-of-thought-tool-use), Anthropic might return multiple messages, expressing chain of thought and tool use. This change generalizes the conversion slightly so that we use the first text response and the first tool call.

Handle more advanced CoT tool use in Anthropic

---

packages/proxy/package.json
packages/proxy/schema/index.ts
packages/proxy/schema/secrets.ts
packages/proxy/src/providers/bedrock.ts
packages/proxy/src/proxy.ts
pnpm-lock.yaml

Add support for claude3 models in Bedrock.

Bedrock support in proxy

---

apis/cloudflare/src/proxy.ts

To be consistent with other services.

Rename to WHITELISTED_ORIGINSt

---

packages/proxy/schema/index.ts
packages/proxy/schema/secrets.ts

Adding costs to type/schema defs to be able to support prices both in custom models and in custom pricing for the OOTB models

Add costs to custom model options

---

packages/proxy/schema/index.ts
packages/proxy/schema/models.ts

Clean up the model definition and adding bedrock definition to the new Claude model.

Update model definitions

---

packages/proxy/schema/models.ts
packages/proxy/schema/secrets.ts

Updating and cleaning up some types related to secrets and models. The error messages are use in the form when creating and updating secrets

Update model and secret types

---

packages/proxy/src/providers/anthropic.ts
packages/proxy/src/proxy.ts

* Zod-ified the anthropic streaming event
* Translate the tool call events into OpenAI's format.

Support anthropic streaming tool calls

---

packages/proxy/src/proxy.ts

CDNs don't like to wait for that long.

Reduce rate limit window

---

packages/proxy/schema/index.ts
packages/proxy/src/proxy.ts

* Capture tool call arguments correctly

Misc fixes

---

packages/proxy/src/providers/openai.ts
packages/proxy/src/proxy.ts

This is useful for people's code and for our playground.

Fake streaming for O1

---

packages/proxy/schema/models.ts

Swapping this makes the default in our custom model dropdown "chat" instead of "completion".

Flip flavors enum

---

apis/cloudflare/package.json
apis/cloudflare/wrangler-template.toml
pnpm-lock.yaml

- Incorporate workerd bug fix for WebSocket pong: https://github.com/cloudflare/workerd/issues/2926
- Improves Node.js compatibility.

Upgrade to wrangler 3.83 & runtime 2024-09-23.

---

packages/proxy/src/proxy.ts

Disable fake streaming in O1

---

.github/workflows/js.yaml
package.json
packages/proxy/turbo.json
pnpm-lock.yaml
turbo.json

To align with our internal build upgrades

Upgrade turborepo

---

packages/proxy/.eslintrc.cjs
packages/proxy/package.json
packages/proxy/src/proxy.ts
pnpm-lock.yaml

Add an ESlint rule for floating promises and fix a bunch of them

Handle some floating promises

---

packages/proxy/package.json
packages/proxy/schema/index.ts
packages/proxy/schema/models.ts
packages/proxy/src/providers/anthropic.ts
packages/proxy/src/providers/bedrock.ts
packages/proxy/src/providers/util.ts
packages/proxy/src/proxy.ts
pnpm-lock.yaml

including system prompts, tool calls, and multimodal.

improve bedrock support

---

packages/proxy/src/proxy.ts

Reverts braintrustdata/braintrust-proxy#151

Revert "Smoothen event source parser by feeding in smaller chunks"

---

packages/proxy/src/proxy.ts

Certain LLM providers can produce 503s in circumstances similar to 429s, and recommend performing the same back-off.

Exponential back-off on 503s

---

packages/proxy/schema/index.ts

will load-balance with groq if both are available for now,
will add some selection/namespacing later.

add cerebras deepseek-r1-distill-llama-70b

---

packages/proxy/src/providers/openai.ts
packages/proxy/src/providers/util.ts

While developing or self hosting, it's useful to have references to local images.

Download local images in the proxy

---

packages/proxy/schema/model_list.json

This is computed by running
```
cd packages/proxy
npx tsx scripts/sync_models.ts check-prices --write
```

Update some model costs using the new script

---

packages/proxy/package.json
packages/proxy/types/anthropic.ts
packages/proxy/types/index.ts

For use on the client in https://github.com/braintrustdata/braintrust/pull/5913

Add anthropic message types

---

packages/proxy/types/anthropic.ts

Export anthropic image part schema

---

.pre-commit-config.yaml
packages/proxy/generated_types.json
packages/proxy/package.json
packages/proxy/schema/index.ts
packages/proxy/scripts/generate_types.ts
packages/proxy/scripts/openapi_zod_client_output_template.hbs
packages/proxy/scripts/tsconfig.json
packages/proxy/src/generated_types.ts
packages/proxy/src/providers/anthropic.ts
packages/proxy/src/providers/bedrock.ts
packages/proxy/src/providers/google.ts
packages/proxy/src/proxy.ts
packages/proxy/types/anthropic.ts
packages/proxy/types/openai.ts
pnpm-lock.yaml

Analogous to https://github.com/braintrustdata/braintrust-sdk/pull/853.

Use autogenerated typespecs instead of braintrust/core

---

apis/node/package.json
package.json
packages/proxy/package.json
pnpm-lock.yaml

To resolve https://github.com/braintrustdata/braintrust-proxy/security/dependabot/54

Upgrade packages

---

packages/proxy/generated_types.json
packages/proxy/schema/index.ts
packages/proxy/src/generated_types.ts

These weren't getting passed through to try prompt before.

Add reasoning params
