braintrustdata/braintrust-proxy

packages/proxy/schema/index.ts, packages/proxy/src/proxy.ts
A benign error. Typescript was not smart enough to recognize that metadata would not be undefined:
```
} else if (
secret.type === "openai" &&
!isEmpty(secret.metadata?.organization_id) &&
E     secret.metadata.organization_id.length > 0     ■ 'secret.metadata' is possibly 'undefined'.
) {
```
=> Fix type error in `proxy.ts`

apis/node/package.json, pnpm-lock.yaml
It's needed to build the node package (standalone)
=> Add typescript to node API devDeps.

packages/proxy/src/proxy.ts
OpenAI now can brotli compress responses, which we were not properly handling
=> Propagate compression headers

packages/proxy/schema/index.ts, packages/proxy/src/proxy.ts
The playground can set both `max_tokens` and `max_tokens_to_sample` (since `max_tokens_to_sample` was listed as a possible Anthropic param).
With these changes, new prompts won't have it, and old prompts will have it stripped out.
=> Ignore (strip out) max_tokens_to_sample from anthropic prompts

apis/node/package.json, pnpm-lock.yaml
Detected by a medium-severity dependabot alert. The issue concerns redirects which I don't think we utilize, but no harm in upgrading the package.
=> Upgrade express package for node api.

apis/cloudflare/src/index.ts, apis/cloudflare/src/proxy.ts, packages/proxy/edge/index.ts
This change refactors the CORS checking logic and then reuses it in the `/` endpoint on the Cloudflare proxy, so we send exactly the CORS headers for the health check as we do for the actual proxy.
=> Generalize CORS further

packages/proxy/src/providers/google.ts
Hi! 
I don't know typescript and I just found out about your project (and I wasn't able to run the proxy locally to test the changes...), but.
When I tried to run an evaluation w/ the EleutherAI eval harness through your public proxy (thank you, BTW!), I got this:
```
openai.BadRequestError: Error code: 400 - {'error': {'code': 400, 'message': 'Invalid JSON payload received. Unknown name "stop" at \'generation_config\': Cannot find field.', 'status': 'INVALID_ARGUMENT', 'details': [{'@type': 'type.googleapis.com/google.rpc.BadRequest', 'fieldViolations': [{'field': 'generation_config', 'description': 'Invalid JSON payload received. Unknown name "stop" at \'generation_config\': Cannot find field.'}]}]}}
```
I assume it's because the 'when to stop generating' strings in OpenAI are passed …
=> Add stop->stopSequences to OpenAI-Google params mapping

packages/proxy/src/providers/anthropic.ts, packages/proxy/src/proxy.ts
Claude doesn't natively support image URLs, so for convenience we should download valid image URLs and convert them to base64 format.
=> Convert image urls to base64 for claude models

packages/proxy/src/proxy.ts, packages/proxy/src/util.ts
If the data is compressed, the way we store cached data only sometimes works. This change updates it to be base64 encoded, and uses that (if present).
We can eventually remove the `text` case, but I didn't want to break people's existing cached data.
=> Fix caching to store binary data

apis/cloudflare/wrangler-template.toml, packages/proxy/src/proxy.ts
Although they appear to be equivalent in Cloudflare, in Node (where this code can be called), `Buffer` is preferred to `btoa`.
=> Use Buffer instead of btoa

apis/cloudflare/package.json
During setup, was sometimes set randomly, even if 8787 was not taken.
=> pin cloudflare proxy ports

packages/proxy/src/proxy.ts
While adding caching elsewhere, I realized we should move towards more standard terminology: `HIT` / `MISS`
=> Fix cache header

packages/proxy/schema/index.ts, packages/proxy/src/encrypt.ts, packages/proxy/src/proxy.ts
* Remove the spread operator from base64 conversion. The spread operator appears to be recursive, internally, so with a sufficiently long input string returned:
```
RangeError: Maximum call stack size exceeded
```
* Remove some default model params.
=> Fix spread operator and default model params

packages/proxy/schema/index.ts
This is only used within Braintrust's product, not the proxy, so removing.
=> Remove MessageTypes

packages/proxy/src/encrypt.ts
For posterity, to remember how necessary it is to keep in sync with main repo utils.
=> Add comment to encrypt file

packages/proxy/src/proxy.ts
I noticed this typo when the Stripe folks were talking about an error they were seeing...
=> Fix typo in console.warn

packages/proxy/src/proxy.ts
This way, you can create a base url that ends with `/btorg/org name` and utilize `OPENAI_BASE_URL` to force a specific org.
=> Allow encoding the org name in the URL

packages/proxy/package.json, packages/proxy/schema/models.ts, packages/proxy/src/providers/anthropic.ts, packages/proxy/src/providers/google.ts, packages/proxy/src/providers/util.ts, packages/proxy/src/proxy.ts, packages/proxy/utils/encrypt.ts, pnpm-lock.yaml
Once we figured out the trick—using `inlineData`—this was quite straightforward. Most of the change is refactoring the image processing code that we built for Anthropic to work for Gemini too.
=> Add support for gemini vision models

packages/proxy/schema/index.ts
I think the values can already be non-strings.
=> Model params can be unknown

packages/proxy/src/providers/anthropic.ts, packages/proxy/src/proxy.ts
They report metrics at different event times than what OpenAI protocol expects...
=> Add anthropic streaming token usage

packages/proxy/utils/tempCredentials.test.ts, packages/proxy/utils/tempCredentials.ts
We should not allow users to "wrap" a temporary credential with another temporary credential. This is fine from a security standpoint because such a credential will fail later while fetching API secrets. However, allowing this is a confusing and perhaps hard to debug behavior, so we prefer to fail fast.
=> Disallow issuing temp credential with another temp credential.

packages/proxy/schema/index.ts
Non-openai models do not support it.
=> Null out response format

packages/proxy/schema/secrets.ts, packages/proxy/src/proxy.ts
Uses the existing `fetchOpenAIFakeStream` method so if a custom provider has the flag `supportsStreaming = false`, we call the method. This allows custom provider endpoints that don't support streaming to work in the playground
=> Add flag to use fake streaming for custom providers

packages/proxy/src/proxy.ts
Type errors can be opaque but in Node.js `fetch` will often throw them (even for rate limit errors). This change tries to harvest the HTTP code out of the type error so we can use our rate-limit handling, etc. if we encounter one.
=> Harvest http codes out of type errors

packages/proxy/src/proxy.ts
It seems like several things, including the event parser (straight up CPU performance), and node's ability to interleave stream segments when running lots of concurrent streams, are worsened by having streams with enormous chunks.
This change splits the stream into newlines, which seems to produce much better results.
=> Smoothen event source parser by feeding in smaller chunks

packages/proxy/src/proxy.ts
Unverts https://github.com/braintrustdata/braintrust-proxy/pull/151 and fixes it. The issue is that when replaying the cache, for the first `0...n-1` chunks, we need to include a newline.
=> Unrevert and fix smoothening changes

packages/proxy/src/proxy.ts
Certain `fetch` implementations, for example Node/Undici, will throw `TypeError`s when there's a 500-* error. This is unfortunate because we lose the mechanics of forwarding these errors along to the client in a way that they can interpret cleanly.
This change converts those errors into a nicely formatted `Response`, so at least it's clear what actually happened.
=> Improve type errors

packages/proxy/package.json, packages/proxy/src/proxy.ts, packages/proxy/src/util.ts, pnpm-lock.yaml
Requests can specify cache behavior and TTL using a limited set of [Cache-Control](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) directives. The following request directives are implemented:
* `no-cache`,`no-store` (these are treated as equivalent)
* `max-age` (up to 90 days)
The `x-bt-cache-ttl` header is also added to request a specific TTL (between 1 second and 90 days)
Note that setting the Cache-Control header will override the behavior of the `x-bt-use-cache` header.  
* Request with `x-bt-cache-ttl: 604800` is equivalent to `x-bt-use-cache: auto`
* Request with `Cache-control: no-cache` is equivalent to `x-bt-use-cache: never`
* Request with `Cache-control: no-store` is equivalent to `x-bt-use-cache: never`
* Request with `Cache-control: max-age=0` is …
=> Implement cache-control directives for max-age, no-cache, and no-store

packages/proxy/schema/models.ts
This PR adds Gemini 2.5 Pro Preview (which has higher rate limits than the experimental version) to the Braintrust AI proxy.
=> [chore] Add Gemini 2.5 Pro Preview to list of models

packages/proxy/schema/models.ts
This PR adds the GPT-4.1 models to Braintrust AI proxy
=> [chore] Add GPT-4.1 models to Braintrust AI proxy

packages/proxy/src/proxy.ts
need to ensure `max_tokens` gets mapped to `max_completion_tokens` for the entire o* line of models
=> handle o1_like model calls

packages/proxy/utils/openai.ts
These functions were assuming the data was a valid chat completion delta, but it may have been undefined, which would cause the code to crash
=> Fix `isChatCompletionChunk` and `isCompletion`

apis/node/package.json, package.json, pnpm-lock.yaml
- Remove '@types/axios' because it is apparently unnecessary, and depends on a version of 'axios' that is flagged by dependabot.
- Pin zod to the same version we have pinned in the internal root repo.
=> Clean up deps

packages/proxy/src/proxy.ts
The minimum an anthropic model can produce now is 4096, so let's increase this default.
=> increase req max tokens

packages/proxy/schema/models.ts
Anthropic doesn't have the `-latest` aliases for these two models anymore, so we should just use the versioned names
https://docs.anthropic.com/en/docs/about-claude/models/all-models
=> Remove Anthropic -latest models

packages/proxy/src/providers/anthropic.ts
Empty messages should be omitted rather than converted to text.
=> fix anthropic translation

packages/proxy/src/proxy.ts
We were previously propagating these error responses directly, but now clarify that they are from the AI provider itself.
=> Nicer errors for persistent 400-class errors

apis/cloudflare/README.md
Latest wrangler requires a space between the command:
```sh
wrangler kv                     🗂️  Manage Workers KV Namespaces
```
->
```sh
wrangler kv --help
wrangler kv
🗂️  Manage Workers KV Namespaces
COMMANDS
wrangler kv namespace  Interact with your Workers KV Namespaces
```
=> docs(cloudflare): fix the syntax for the wrangler kv command

packages/proxy/generated_types.json, packages/proxy/schema/models.ts, packages/proxy/src/generated_types.ts, packages/proxy/src/proxy.ts, packages/proxy/src/util.test.ts, packages/proxy/src/util.ts
We really only need the `_urljoin` function, which is simple enough to just copy-paste over.
=> Eliminate dependency on `@braintrust/core`.

packages/proxy/src/proxy.ts
I did this [during testing](https://github.com/braintrustdata/braintrust-proxy/pull/302/files#diff-f9467ab4882d85829b5ae101d098958cb1f6dafcb726ed6baee1dc26a5e34e9bR572-L573), but I didn't add coverage to test what would be difference. Because it's on the critical path but not for the changes https://github.com/braintrustdata/braintrust-proxy/pull/302 I'd like to revert this change and come back to it later. 
With the revert the tests could see an undefined status code (for the 200 response case), but that's the previous behavior before my change.
=> Revert a small setStatusCode change
